name: fhcs
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  loader_overlay: ^5.0.0
  skeletonizer: ^1.4.3
  go_router: ^14.8.1
  awesome_extensions: ^2.0.21
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  percent_indicator: ^4.2.4
  phone_form_field: ^10.0.5
  form_validator: ^2.1.1
  image_picker: ^1.1.2
  animated_custom_dropdown: ^3.1.1
  intl: ^0.20.2
  pinput: ^5.0.1
  currency_text_input_formatter: ^2.3.0
  flutter_multi_formatter: ^2.13.7
  get_it: ^8.0.3
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3
  elegant_notification: ^2.4.4
  loading_indicator: ^3.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_paystack_plus: ^2.2.1
  flutter_paystack_max: ^1.0.6
  currency_formatter: ^2.2.3
  flutter_spinkit: ^5.2.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tbd/
    # - assets/fonts/
    - assets/svgs/
    - assets/translations/
