name: fhcs
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  loader_overlay: ^5.0.0
  skeletonizer: ^1.4.3
  go_router: ^14.8.1
  awesome_extensions: ^2.0.21
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  percent_indicator: ^4.2.4
  phone_form_field: ^10.0.5
  form_validator: ^2.1.1
  image_picker: ^1.1.2
  animated_custom_dropdown: ^3.1.1
  intl: ^0.19.0
  pinput: ^5.0.1
  currency_text_input_formatter: ^2.3.0
  flutter_multi_formatter: ^2.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tbd/
    - assets/fonts/
    - assets/svgs/
    - assets/translations/
